version: "2"
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash
      - elasticsearch

  metadata-service:
    image: vertx/metadataservice
    expose:
      - "8190"
    ports:
      - "8190:8190"
    links:
      - logstash
    depends_on:
      - logstash

  account-service:
    image: vertx/accountservice
    expose:
      - "8090"
    ports:
      - "8090:8090"
    links:
      - logstash
    depends_on:
          - logstash

  api-gateway:
    image: vertx/gateway
    expose:
      - "8050"
    ports:
      - "8050:8050"
    links:
      - logstash
      - metadata-service
      - account-service

