version: "2"
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash