apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-compose.yml convert
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    io.kompose.service: account-service
  type: LoadBalancer
status:
  loadBalancer: {}
